### ISSUE TITLE
Look into zsh-autoenv

### ISSUE THREAD

**Issue by blueyed** [JoshAshby/dots#1]
Re https://github.com/JoshAshby/dots/blob/master/zsh/functions.zsh#L44 you might be interested in https://github.com/Tarrasch/zsh-autoenv.

Cheers! :)

**Comment by JoshAshby** [comment]
I'm going to close this issue as I've moved on to using FiSH, and tooling/my own workflows have evolved to not have a need for the autoenv setup anymore, but thanks!
